In [1]:
import pandas as pd

# Series Object

In [2]:
s1 = pd.Series([45,35,67,43,87])

In [3]:
s1

0    45
1    35
2    67
3    43
4    87
dtype: int64

In [4]:
s2 = pd.Series([34,23,87.40,67,89,54])

In [5]:
s2

0    34.0
1    23.0
2    87.4
3    67.0
4    89.0
5    54.0
dtype: float64

In [6]:
s2.size

6

In [7]:
s2[4]

89.0

In [8]:
s2[3] = 78
s2

0    34.0
1    23.0
2    87.4
3    78.0
4    89.0
5    54.0
dtype: float64

In [10]:
s3 = pd.Series([34,56,78,65,43,21], index= range(100,106))

In [11]:
s3

100    34
101    56
102    78
103    65
104    43
105    21
dtype: int64

In [14]:
s3[102]

78

In [15]:
pwd

'/home/aditya/mitu NOV 23'

# Dataframe Object

In [16]:
roll = pd.Series([1,2,3,4,5])
name = pd.Series(['Akash','Riya','Raj','Revati','Somesh'])
marks = pd.Series([78.66,76.99,56.76,84.76,71.76,])

In [17]:
df = pd.DataFrame({
    'roll' : roll,
    'name' : name,
    'marks' : marks
})

In [18]:
df

   roll    name  marks
0     1   Akash  78.66
1     2    Riya  76.99
2     3     Raj  56.76
3     4  Revati  84.76
4     5  Somesh  71.76

In [19]:
df.shape

(5, 3)

In [20]:
df.size

15

In [21]:
df.columns

Index(['roll', 'name', 'marks'], dtype='object')

#### current working directory

In [24]:
import os
os.getcwd()

'/home/aditya/mitu NOV 23'

#### download the dataset

In [25]:
# Loction -> https://mitu.co.in/dataset
# download -> all student datasets and store them in cwd

#### import the dataset

In [26]:
df = pd.read_csv('student.csv')

In [27]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [28]:
df1 = pd.read_csv('student1.csv')

In [29]:
df1

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [30]:
headers = ['A','B','C','D','E']
df1 = pd.read_csv('student1.csv', names = headers)

In [31]:
df1

    A        B   C      D   E
0   1     anil  TE  56.77  22
1   2     amit  TE  59.77  21
2   3   aniket  BE  76.88  19
3   4  ajinkya  TE  69.66  20
4   5     asha  TE  63.28  20
5   6   ayesha  BE  49.55  20
6   7     amar  BE  65.34  19
7   8    amita  BE  68.33  23
8   9     amol  TE  56.75  20
9  10    anmol  BE  78.66  21

In [32]:
df2 = pd.read_csv('student3.tsv', sep = '\t')

In [33]:
df2

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [35]:
df = pd.read_csv('student.csv')

In [36]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [37]:
df.shape

(10, 5)

In [38]:
df.size

50

In [39]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [40]:
df.T

,0,1,2,3,4,5,6,7,8,9
roll,1,2,3,4,5,6,7,8,9,10
name,anil,amit,aniket,ajinkya,asha,ayesha,amar,amita,amol,anmol
class,TE,TE,BE,TE,TE,BE,BE,BE,TE,BE
marks,56.77,59.77,76.88,69.66,63.28,49.55,65.34,68.33,56.75,78.66
age,22,21,19,20,20,20,19,23,20,21

In [41]:
df.dtypes

roll       int64
name      object
class     object
marks    float64
age        int64
dtype: object

In [42]:
df.values

array([[1, 'anil', 'TE', 56.77, 22],
       [2, 'amit', 'TE', 59.77, 21],
       [3, 'aniket', 'BE', 76.88, 19],
       [4, 'ajinkya', 'TE', 69.66, 20],
       [5, 'asha', 'TE', 63.28, 20],
       [6, 'ayesha', 'BE', 49.55, 20],
       [7, 'amar', 'BE', 65.34, 19],
       [8, 'amita', 'BE', 68.33, 23],
       [9, 'amol', 'TE', 56.75, 20],
       [10, 'anmol', 'BE', 78.66, 21]], dtype=object)

In [46]:
df.head()

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [48]:
df.head(4)

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20

In [49]:
df.tail()

   roll    name class  marks  age
5     6  ayesha    BE  49.55   20
6     7    amar    BE  65.34   19
7     8   amita    BE  68.33   23
8     9    amol    TE  56.75   20
9    10   anmol    BE  78.66   21

In [50]:
df.tail(3)

   roll   name class  marks  age
7     8  amita    BE  68.33   23
8     9   amol    TE  56.75   20
9    10  anmol    BE  78.66   21

In [52]:
df.sum()

roll                                                    55
name     anilamitaniketajinkyaashaayeshaamaramitaamolanmol
class                                 TETEBETETEBEBEBETEBE
marks                                               644.99
age                                                    205
dtype: object

In [53]:
df.max()

roll         10
name     ayesha
class        TE
marks     78.66
age          23
dtype: object

In [54]:
df.min()

roll           1
name     ajinkya
class         BE
marks      49.55
age           19
dtype: object

In [56]:
df.count()

roll     10
name     10
class    10
marks    10
age      10
dtype: int64

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    10 non-null     int64
 1   name    10 non-null     object
 2   class   10 non-null     object
 3   marks   10 non-null     float64
 4   age     10 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 532.0+ bytes

In [58]:
df.describe()

           roll      marks        age
count  10.00000  10.000000  10.000000
mean    5.50000  64.499000  20.500000
std     3.02765   9.207179   1.269296
min     1.00000  49.550000  19.000000
25%     3.25000  57.520000  20.000000
50%     5.50000  64.310000  20.000000
75%     7.75000  69.327500  21.000000
max    10.00000  78.660000  23.000000

#### data sclicing

In [60]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [62]:
df.iloc[3:8,1:4]

      name class  marks
3  ajinkya    TE  69.66
4     asha    TE  63.28
5   ayesha    BE  49.55
6     amar    BE  65.34
7    amita    BE  68.33

In [63]:
x = df.iloc[3:8,1:4]
x

      name class  marks
3  ajinkya    TE  69.66
4     asha    TE  63.28
5   ayesha    BE  49.55
6     amar    BE  65.34
7    amita    BE  68.33

In [64]:
df.iloc[3:8]   # by default takes all the columns

   roll     name class  marks  age
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23

In [67]:
df.iloc[:,1:4]  # will take all the rows

      name class  marks
0     anil    TE  56.77
1     amit    TE  59.77
2   aniket    BE  76.88
3  ajinkya    TE  69.66
4     asha    TE  63.28
5   ayesha    BE  49.55
6     amar    BE  65.34
7    amita    BE  68.33
8     amol    TE  56.75
9    anmol    BE  78.66

In [68]:
df.iloc[2:,1:4]

      name class  marks
2   aniket    BE  76.88
3  ajinkya    TE  69.66
4     asha    TE  63.28
5   ayesha    BE  49.55
6     amar    BE  65.34
7    amita    BE  68.33
8     amol    TE  56.75
9    anmol    BE  78.66

In [69]:
df.iloc[2:,1:]

      name class  marks  age
2   aniket    BE  76.88   19
3  ajinkya    TE  69.66   20
4     asha    TE  63.28   20
5   ayesha    BE  49.55   20
6     amar    BE  65.34   19
7    amita    BE  68.33   23
8     amol    TE  56.75   20
9    anmol    BE  78.66   21

In [70]:
df.iloc[2:,:]

   roll     name class  marks  age
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [71]:
df.iloc[:,1]

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [72]:
df.iloc[[3,5,7],[1,3]]

      name  marks
3  ajinkya  69.66
5   ayesha  49.55
7    amita  68.33

In [73]:
df.loc[:,'name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [74]:
df.loc[:,['name','marks']]

      name  marks
0     anil  56.77
1     amit  59.77
2   aniket  76.88
3  ajinkya  69.66
4     asha  63.28
5   ayesha  49.55
6     amar  65.34
7    amita  68.33
8     amol  56.75
9    anmol  78.66

In [75]:
df['name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [76]:
df[['name','marks']]

      name  marks
0     anil  56.77
1     amit  59.77
2   aniket  76.88
3  ajinkya  69.66
4     asha  63.28
5   ayesha  49.55
6     amar  65.34
7    amita  68.33
8     amol  56.75
9    anmol  78.66

In [77]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [81]:
df.drop(4)

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [82]:
df.drop([4,6,7])

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
5     6   ayesha    BE  49.55   20
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [85]:
df.drop('name', axis = 1)

   roll class  marks  age
0     1    TE  56.77   22
1     2    TE  59.77   21
2     3    BE  76.88   19
3     4    TE  69.66   20
4     5    TE  63.28   20
5     6    BE  49.55   20
6     7    BE  65.34   19
7     8    BE  68.33   23
8     9    TE  56.75   20
9    10    BE  78.66   21

In [91]:
df.drop(['name','class','marks'], axis = 1)

   roll  age
0     1   22
1     2   21
2     3   19
3     4   20
4     5   20
5     6   20
6     7   19
7     8   23
8     9   20
9    10   21

#### Renaming

In [88]:
cols = {'roll' : 'id', 'marks' : 'grade'}

In [89]:
df.rename(columns=cols)  # renamed columns

   id     name class  grade  age
0   1     anil    TE  56.77   22
1   2     amit    TE  59.77   21
2   3   aniket    BE  76.88   19
3   4  ajinkya    TE  69.66   20
4   5     asha    TE  63.28   20
5   6   ayesha    BE  49.55   20
6   7     amar    BE  65.34   19
7   8    amita    BE  68.33   23
8   9     amol    TE  56.75   20
9  10    anmol    BE  78.66   21

In [92]:
ind = {1: 'first', 5: 'fifth'}  # rename index

In [93]:
df.rename(index = ind)

       roll     name class  marks  age
0         1     anil    TE  56.77   22
first     2     amit    TE  59.77   21
2         3   aniket    BE  76.88   19
3         4  ajinkya    TE  69.66   20
4         5     asha    TE  63.28   20
fifth     6   ayesha    BE  49.55   20
6         7     amar    BE  65.34   19
7         8    amita    BE  68.33   23
8         9     amol    TE  56.75   20
9        10    anmol    BE  78.66   21

#### iterations

In [95]:
for x in df:
    print(x)

roll
name
class
marks
age

In [96]:
for x in df:
    print(df[x])

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: roll, dtype: int64
0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object
0    TE
1    TE
2    BE
3    TE
4    TE
5    BE
6    BE
7    BE
8    TE
9    BE
Name: class, dtype: object
0    56.77
1    59.77
2    76.88
3    69.66
4    63.28
5    49.55
6    65.34
7    68.33
8    56.75
9    78.66
Name: marks, dtype: float64
0    22
1    21
2    19
3    20
4    20
5    20
6    19
7    23
8    20
9    21
Name: age, dtype: int64

#### sort the data

In [97]:
df.sort_values(by='class')

   roll     name class  marks  age
2     3   aniket    BE  76.88   19
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
9    10    anmol    BE  78.66   21
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
8     9     amol    TE  56.75   20

In [98]:
df.sort_values(by='marks')

   roll     name class  marks  age
5     6   ayesha    BE  49.55   20
8     9     amol    TE  56.75   20
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
4     5     asha    TE  63.28   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
3     4  ajinkya    TE  69.66   20
2     3   aniket    BE  76.88   19
9    10    anmol    BE  78.66   21

In [99]:
df.sort_values(by=['class','marks'])

   roll     name class  marks  age
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
2     3   aniket    BE  76.88   19
9    10    anmol    BE  78.66   21
8     9     amol    TE  56.75   20
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
4     5     asha    TE  63.28   20
3     4  ajinkya    TE  69.66   20

In [101]:
df.sort_values(by='marks', ascending = False)

   roll     name class  marks  age
9    10    anmol    BE  78.66   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
7     8    amita    BE  68.33   23
6     7     amar    BE  65.34   19
4     5     asha    TE  63.28   20
1     2     amit    TE  59.77   21
0     1     anil    TE  56.77   22
8     9     amol    TE  56.75   20
5     6   ayesha    BE  49.55   20

#### methods on Series

In [102]:
df['marks'].sum()

644.9899999999999

In [103]:
df['marks'].count()

10

In [104]:
df['marks'].median()

64.31

### string methods

In [106]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [105]:
df['name'].str.upper()

0       ANIL
1       AMIT
2     ANIKET
3    AJINKYA
4       ASHA
5     AYESHA
6       AMAR
7      AMITA
8       AMOL
9      ANMOL
Name: name, dtype: object

In [108]:
df['name'].str.title()

0       Anil
1       Amit
2     Aniket
3    Ajinkya
4       Asha
5     Ayesha
6       Amar
7      Amita
8       Amol
9      Anmol
Name: name, dtype: object

In [109]:
df['name'].str.len()

0    4
1    4
2    6
3    7
4    4
5    6
6    4
7    5
8    4
9    5
Name: name, dtype: int64

In [110]:
df['name'].str.startswith('an')

0     True
1    False
2     True
3    False
4    False
5    False
6    False
7    False
8    False
9     True
Name: name, dtype: bool

In [111]:
df['name'].str.contains('n')

0     True
1    False
2     True
3     True
4    False
5    False
6    False
7    False
8    False
9     True
Name: name, dtype: bool

In [113]:
df['name'].str.repeat(3)

0             anilanilanil
1             amitamitamit
2       aniketaniketaniket
3    ajinkyaajinkyaajinkya
4             ashaashaasha
5       ayeshaayeshaayesha
6             amaramaramar
7          amitaamitaamita
8             amolamolamol
9          anmolanmolanmol
Name: name, dtype: object

#### Add or modify Columns

In [114]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [115]:
df['roll'] = df['roll'] + 100

In [116]:
df

   roll     name class  marks  age
0   101     anil    TE  56.77   22
1   102     amit    TE  59.77   21
2   103   aniket    BE  76.88   19
3   104  ajinkya    TE  69.66   20
4   105     asha    TE  63.28   20
5   106   ayesha    BE  49.55   20
6   107     amar    BE  65.34   19
7   108    amita    BE  68.33   23
8   109     amol    TE  56.75   20
9   110    anmol    BE  78.66   21

In [117]:
gender = ['m','m','m','m','f','f','m','f','m','m']

In [118]:
df['gender'] = gender

In [119]:
df

   roll     name class  marks  age gender
0   101     anil    TE  56.77   22      m
1   102     amit    TE  59.77   21      m
2   103   aniket    BE  76.88   19      m
3   104  ajinkya    TE  69.66   20      m
4   105     asha    TE  63.28   20      f
5   106   ayesha    BE  49.55   20      f
6   107     amar    BE  65.34   19      m
7   108    amita    BE  68.33   23      f
8   109     amol    TE  56.75   20      m
9   110    anmol    BE  78.66   21      m

In [120]:
df['gender'].value_counts()

gender
m    7
f    3
Name: count, dtype: int64

In [121]:
df['class'].value_counts()

class
TE    5
BE    5
Name: count, dtype: int64

In [122]:
df['gender'].mode() # mode-> value which is repeating max no. of times

0    m
Name: gender, dtype: object

#### grouping operations

In [125]:
gr = df.groupby('class')

In [128]:
gr.groups

{'BE': [2, 5, 6, 7, 9], 'TE': [0, 1, 3, 4, 8]}

In [126]:
gr.get_group('TE')

   roll     name class  marks  age gender
0   101     anil    TE  56.77   22      m
1   102     amit    TE  59.77   21      m
3   104  ajinkya    TE  69.66   20      m
4   105     asha    TE  63.28   20      f
8   109     amol    TE  56.75   20      m

In [127]:
gr.get_group('BE')

   roll    name class  marks  age gender
2   103  aniket    BE  76.88   19      m
5   106  ayesha    BE  49.55   20      f
6   107    amar    BE  65.34   19      m
7   108   amita    BE  68.33   23      f
9   110   anmol    BE  78.66   21      m

In [129]:
gr['marks'].agg(max)

/tmp/ipykernel_4890/1945279628.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  gr['marks'].agg(max)

class
BE    78.66
TE    69.66
Name: marks, dtype: float64

In [130]:
df

   roll     name class  marks  age gender
0   101     anil    TE  56.77   22      m
1   102     amit    TE  59.77   21      m
2   103   aniket    BE  76.88   19      m
3   104  ajinkya    TE  69.66   20      m
4   105     asha    TE  63.28   20      f
5   106   ayesha    BE  49.55   20      f
6   107     amar    BE  65.34   19      m
7   108    amita    BE  68.33   23      f
8   109     amol    TE  56.75   20      m
9   110    anmol    BE  78.66   21      m

In [133]:
df.drop('gender', axis = 1, inplace=True)

In [134]:
df

   roll     name class  marks  age
0   101     anil    TE  56.77   22
1   102     amit    TE  59.77   21
2   103   aniket    BE  76.88   19
3   104  ajinkya    TE  69.66   20
4   105     asha    TE  63.28   20
5   106   ayesha    BE  49.55   20
6   107     amar    BE  65.34   19
7   108    amita    BE  68.33   23
8   109     amol    TE  56.75   20
9   110    anmol    BE  78.66   21

In [138]:
city = ['pune','pune','nagpur','delhi','mumbai','pune','mumbai','pune',
            'mumbai','delhi']

In [140]:
newdf = pd.DataFrame({
    'roll': range(101,111),
    'gender': gender,
    'city': city
})

In [141]:
newdf

   roll gender    city
0   101      m    pune
1   102      m    pune
2   103      m  nagpur
3   104      m   delhi
4   105      f  mumbai
5   106      f    pune
6   107      m  mumbai
7   108      f    pune
8   109      m  mumbai
9   110      m   delhi

In [142]:
pd.merge(df, newdf, on='roll')

   roll     name class  marks  age gender    city
0   101     anil    TE  56.77   22      m    pune
1   102     amit    TE  59.77   21      m    pune
2   103   aniket    BE  76.88   19      m  nagpur
3   104  ajinkya    TE  69.66   20      m   delhi
4   105     asha    TE  63.28   20      f  mumbai
5   106   ayesha    BE  49.55   20      f    pune
6   107     amar    BE  65.34   19      m  mumbai
7   108    amita    BE  68.33   23      f    pune
8   109     amol    TE  56.75   20      m  mumbai
9   110    anmol    BE  78.66   21      m   delhi

In [143]:
newdf = pd.read_csv('student5.csv')
newdf

   roll     name class  marks  age
0     1   surbhi    TE  67.44   23
1     2    sujay    TE  74.12   22
2     3  subhash    BE  82.44   21
3     4   sachin    TE  59.33   21
4     5  shalini    TE  63.45   20

In [145]:
pd.concat([df, newdf], ignore_index=True)

    roll     name class  marks  age
0    101     anil    TE  56.77   22
1    102     amit    TE  59.77   21
2    103   aniket    BE  76.88   19
3    104  ajinkya    TE  69.66   20
4    105     asha    TE  63.28   20
5    106   ayesha    BE  49.55   20
6    107     amar    BE  65.34   19
7    108    amita    BE  68.33   23
8    109     amol    TE  56.75   20
9    110    anmol    BE  78.66   21
10     1   surbhi    TE  67.44   23
11     2    sujay    TE  74.12   22
12     3  subhash    BE  82.44   21
13     4   sachin    TE  59.33   21
14     5  shalini    TE  63.45   20